application: puzzlegame
version: 1
runtime: go 
api_version: go1 

handlers: 
- url: /(.*\.(jpg|gif|png|css|html|js|go))
  static_files: \1
  upload: (.*\.(jpg|gif|png|css|html|js))

- url: /animations
  static_dir: \animations
  

- url: /.*
  script: _go_app

- url: /PuzzleGame.html
  static_files: \PuzzleGame.html
  upload: \PuzzleGame.htmlW

- url: /updateScore
  script: _go_app

- url: /getPuzzle
  script: HelloStuff.go

- url: /uploadForm
  script: HelloStuff.go

- url: /upload
  script: HelloStuff.go

- url: /uploadPuzzle
  script: HelloStuff.go

- url: /login
  script: HelloStuff.go


  
